### ISSUE TITLE
Structure bdd ?

### ISSUE THREAD

**Issue by Tchoow** [iyed-dev/Elevecomax#1]
Hello, :)

Je regarde ton fichier d'import SQL et je remarque que tu fais 3 tables élèves, prof, parent.
Cependant, la plupart des infos se répètent.

Ça n'aurait pas été plus propre de faire juste une table user, ou tu rajoutes une colonne "type" ou "statut" pour identifier le type
d'utilisateur ?
Idem avec pourquoi pas des autorisations :)

La bise,
Tchoow

**Comment by iyed-dev** [comment]
Bahahhaha Salut Tchoow !

Alors je t’explique, ce code date d’il y’a environ 2 ans donc bon je
voulais le mettre en ligne malgré les défauts du programme.

Pleins de bisous sur la foufoune Tchoow !

Cordialement, Iyed le bg

**Comment by Tchoow** [comment]
Ok !
Des bisous,
Tchoow le giga bg
